<?php

use Fisharebest\Webtrees\I18N; ?>
<?php

use Fisharebest\Webtrees\View; ?>
<?php

use Cissee\WebtreesExt\ModuleView; ?>

<?php
echo $outputBeforeTab->getMain();
View::push('javascript');
echo $outputBeforeTab->getScript();
View::endpush();
?>

<div class="wt-sources-tab py-4">
    <table class="table table-sm wt-facts-table" role="presentation">
        <tbody>
            <tr>
                <td>
                    <label>
                        <input id="show-date-differences-rwh" type="checkbox" data-toggle="collapse" data-target=".wt-date-difference-rwh">
                        <?= I18N::translate('Date differences') ?>
                    </label>
                    <?php
                    //[RC] PATCHED
                    echo $outputInDescriptionbox->getMain();
                    View::push('javascript');
                    echo $outputInDescriptionbox->getScript();
                    View::endpush();
                    ?>
                </td>
            </tr>
            <?php
            //[RC] PATCHED
            echo $outputAfterDescriptionbox->getMain();
            View::push('javascript');
            echo $outputAfterDescriptionbox->getScript();
            View::endpush();
            ?>
        </tbody>
    </table>

    <?php if (empty($parent_families) && $can_edit) : ?>
      <table class="table table-sm wt-facts-table" role="presentation">
          <tbody>
              <tr>
                  <td>
                      <a href="<?= e(route('add-parent-to-individual', ['ged' => $individual->tree()->name(), 'xref' => $individual->xref(), 'gender' => 'M'])) ?>">
                          <?= I18N::translate('Add a father') ?>
                      </a>
                  </td>
              </tr>
              <tr>
                  <td>
                      <a href="<?= e(route('add-parent-to-individual', ['ged' => $individual->tree()->name(), 'xref' => $individual->xref(), 'gender' => 'F'])) ?>">
                          <?= I18N::translate('Add a mother') ?>
                      </a>
                  </td>
              </tr>
          </tbody>
      </table>
    <?php endif ?>

    <!-- Parents -->
    <?php foreach ($parent_families as $family): ?>
      <?=
      ModuleView::make($this->module_directory, 'family', [
          'individual' => $individual,
          'family' => $family,
          'type' => 'FAMC',
          'label' => $individual->getChildFamilyLabel($family),
          'fam_access_level' => $fam_access_level,
          //[RC] additions
          'outputFamilyAfterSubHeadersFunction' => $outputFamilyAfterSubHeadersFunction,
          'printFamilyChild' => $printFamilyChild
      ])
      ?>
    <?php endforeach ?>

    <!-- step-parents -->
    <?php foreach ($step_parent_families as $family): ?>
      <?=
      ModuleView::make($this->module_directory, 'family', [
          'individual' => $individual,
          'family' => $family,
          'type' => 'FAMC',
          'label' => $individual->getStepFamilyLabel($family),
          'fam_access_level' => $fam_access_level,
          //[RC] additions
          'outputFamilyAfterSubHeadersFunction' => $outputFamilyAfterSubHeadersFunction,
          'printFamilyChild' => $printFamilyChild
      ])
      ?>
    <?php endforeach ?>

    <!-- spouses -->
    <?php foreach ($spouse_families as $family): ?>
      <?=
      ModuleView::make($this->module_directory, 'family', [
          'individual' => $individual,
          'family' => $family,
          'type' => 'FAMS',
          'label' => $individual->getSpouseFamilyLabel($family),
          'fam_access_level' => $fam_access_level,
          //[RC] additions
          'outputFamilyAfterSubHeadersFunction' => $outputFamilyAfterSubHeadersFunction,
          'printFamilyChild' => $printFamilyChild
      ])
      ?>
    <?php endforeach ?>

    <!-- step-children -->
    <?php foreach ($step_child_familiess as $family): ?>
      <?=
      ModuleView::make($this->module_directory, 'family', [
          'individual' => $individual,
          'family' => $family,
          'type' => 'FAMS',
          'label' => $family->fullName(),
          'fam_access_level' => $fam_access_level,
          //[RC] additions
          'outputFamilyAfterSubHeadersFunction' => $outputFamilyAfterSubHeadersFunction,
          'printFamilyChild' => $printFamilyChild
      ])
      ?>
    <?php endforeach ?>

    <?php if ($can_edit) : ?>
      <br>
      <table class="table table-sm wt-facts-table" role="presentation">
          <tbody>
              <?php if (count($spouse_families) > 1) : ?>
                <tr>
                    <td>
                        <a href="<?= e(route('reorder-spouses', ['ged' => $individual->tree()->name(), 'xref' => $individual->xref()])) ?>">
                            <?= I18N::translate('Re-order families') ?>
                        </a>
                    </td>
                </tr>
              <?php endif ?>
              <tr>
                  <td>
                      <a href="<?= e(route('link-child-to-family', ['ged' => $individual->tree()->name(), 'xref' => $individual->xref()])) ?>">
                          <?= I18N::translate('Link this individual to an existing family as a child') ?>
                      </a>
                  </td>
              </tr>

              <tr>
                  <td>
                      <a href="<?= e(route('add-spouse-to-individual', ['ged' => $individual->tree()->name(), 'xref' => $individual->xref()])) ?>">
                          <?php if ($individual->sex() !== 'F') : ?>
                            <?= I18N::translate('Add a wife') ?>
                          <?php else : ?>
                            <?= I18N::translate('Add a husband') ?>
                          <?php endif ?>
                      </a>
                  </td>
              </tr>

              <tr>
                  <td>
                      <a href="<?= e(route('link-spouse-to-individual', ['ged' => $individual->tree()->name(), 'xref' => $individual->xref()])) ?>">
                          <?php if ($individual->sex() !== 'F') : ?>
                            <?= I18N::translate('Add a wife using an existing individual') ?>
                          <?php else : ?>
                            <?= I18N::translate('Add a husband using an existing individual') ?>
                          <?php endif ?>
                      </a>
                  </td>
              </tr>

              <tr>
                  <td>
                      <a href="<?= e(route('add-child-to-individual', ['ged' => $individual->tree()->name(), 'xref' => $individual->xref(), 'gender' => 'U'])) ?>">
                          <?= I18N::translate('Add a child to create a one-parent family') ?>
                      </a>
                  </td>
              </tr>
          </tbody>
      </table>
    <?php endif ?>
</div>

<?php
echo $outputAfterTab->getMain();
View::push('javascript');
echo $outputAfterTab->getScript();
View::endpush();
?>

<?php View::push('javascript') ?>
<script>
  'use strict';

  persistent_toggle("show-date-differences-rwh");
</script>
<?php View::endpush() ?>
